---
- name: Install Software
  hosts: all
  become: true
   
  tasks:

    - name: Install the latest version of Task 1 Software
      ansible.builtin.dnf:
        name: 
         - httpd
         - mariadb-server
         - firefox
         - git
        state: latest